version: "3"

services:
  elasticsearch:
    image: elasticsearch:5.6
    ports:
      - "9200:9200"
    environment:
      ES_JAVA_OPTS: -Xms512m -Xmx512m
    volumes:
      - es_data:/usr/share/elasticsearch/data

  redis:
    image: redis

  karaoke-server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: ts-node bin/server.ts
    environment:
      DB_HOST: elasticsearch
      DB_PORT: 9200
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - ./backend:/var/app
    links:
      - redis
      - elasticsearch
    ports:
      - "80:80"

  admin-panel:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    

volumes:
  es_data:
