version: "3"

services:
  elasticsearch:
    image: elasticsearch:2.3
    ports:
      - "9200:9200"


  redis:
    image: redis

  karaoke-server:
    build:
      context: .
      dockerfile: Dockerfile
    command: ts-node bin/server.ts
    environment:
      DB_HOST: elasticsearch
      DB_PORT: 9200
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - ./app:/var/app
    links:
      - redis
      - elasticsearch
    ports:
      - "80:80"
